
[colors.primary]
background = '#17130b'
foreground = '#ebe1d4'

[colors.cursor]
cursor = '#e7c26c'
text = '#3f2e00'

[colors.vi_mode_cursor]
cursor = '#e7c26c'
text = '#3f2e00'

[colors.search.matches]
foreground = '#1c361d'
background = '#afcfab'

[colors.search.focused_match]
foreground = '#3f2e00'
background = '#e7c26c'

[colors.footer_bar]
foreground = '#ebe1d4'
background = '#231f17'

[colors.hints.start]
foreground = '#3a2f15'
background = '#d7c4a0'

[colors.hints.end]
foreground = '#3a2f15'
background = '#52452a'

[colors.selection]
text = '#3f2e00'
background = '#e7c26c'

[colors.normal]
black   = '#17130b'
red     = '#ffb4ab'
green   = '#afcfab'
yellow  = '#d7c4a0'
blue    = '#e7c26c'
magenta = '#afcfab'
cyan    = '#d7c4a0'
white   = '#d0c5b4'

[colors.bright]
black   = '#3e392f'
red     = '#93000a'
green   = '#324d31'
yellow  = '#52452a'
blue    = '#5a4300'
magenta = '#cbebc5'
cyan    = '#f4e0bb'
white   = '#ebe1d4'

[colors.dim]
black   = '#110e07'
red     = '#ffdad6'
green   = '#cbebc5'
yellow  = '#f4e0bb'
blue    = '#ffdf9a'
magenta = '#062109'
cyan    = '#241a04'
white   = '#999080'
