
[colors.primary]
background = '#11140f'
foreground = '#e0e4da'

[colors.cursor]
cursor = '#a3d398'
text = '#0e380d'

[colors.vi_mode_cursor]
cursor = '#a3d398'
text = '#0e380d'

[colors.search.matches]
foreground = '#00363a'
background = '#a0cfd3'

[colors.search.focused_match]
foreground = '#0e380d'
background = '#a3d398'

[colors.footer_bar]
foreground = '#e0e4da'
background = '#1d211b'

[colors.hints.start]
foreground = '#263422'
background = '#baccb2'

[colors.hints.end]
foreground = '#263422'
background = '#3c4b38'

[colors.selection]
text = '#0e380d'
background = '#a3d398'

[colors.normal]
black   = '#11140f'
red     = '#ffb4ab'
green   = '#a0cfd3'
yellow  = '#baccb2'
blue    = '#a3d398'
magenta = '#a0cfd3'
cyan    = '#baccb2'
white   = '#c2c8bc'

[colors.bright]
black   = '#363a34'
red     = '#93000a'
green   = '#1e4d51'
yellow  = '#3c4b38'
blue    = '#265022'
magenta = '#bcebef'
cyan    = '#d6e8ce'
white   = '#e0e4da'

[colors.dim]
black   = '#0b0f0a'
red     = '#ffdad6'
green   = '#bcebef'
yellow  = '#d6e8ce'
blue    = '#bef0b2'
magenta = '#002022'
cyan    = '#111f0f'
white   = '#8c9388'
