#!/bin/bash
source "${BASH_SOURCE[0]%/*}/../../hypr/scripts/lib/common.sh"

CURRENT=$(cat "$N4P1X_CURRENT_THEME" 2>/dev/null)

SELECTED=$(ls -d "$N4P1X_DIR"/*/ | xargs -n1 basename | grep -v "current\|hooks\|base\|dynamic" | sort | \
    rofi -dmenu -i -p "Theme" -config ~/.config/rofi/config.rasi)

[[ -z "$SELECTED" ]] && exit 0
[[ "$SELECTED" == "$CURRENT" ]] && exit 0

N4P1x switch "$SELECTED"
