
[mgr]
cwd = { fg = "#ecdfe5" }

find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

marker_copied = { fg = "#ff8f69", bg = "#ff8f69" }
marker_cut = { fg = "#ffdbcf", bg = "#ffdbcf" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f5b9a4", bg = "#f5b9a4" }

count_copied = { fg = "#321206", bg = "#ffdbcf" }
count_cut = { fg = "#321206", bg = "#ffdbcf" }
count_selected = { fg = "#4d1f46", bg = "#f5b9a4" }

border_symbol = " "
border_style  = { fg = "#f3b2e3" }




[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

perm_type = { fg = "#a45c8b" }
perm_read = { fg = "#ff6836" }
perm_write = { fg = "#e64f1a" }
perm_exec = { fg = "#ff2b12" }
perm_sep = { fg = "#ff3ec0" }

progress_label = { bold = true }
progress_normal = { fg = "#f3b2e3", bg = "#3f373c" }
progress_error = { fg = "#ffb4ab", bg = "#3f373c" }

[mode]
normal_main = { bg = "#f3b2e3", fg = "#4d1f46", bold = true }
normal_alt  = { bg = "#4e444b", fg = "#d2c2cb" }

select_main = { bg = "#dbbed1", fg = "#3e2a39", bold = true }
select_alt  = { bg = "#4e444b", fg = "#d2c2cb" }

unset_main = { bg = "#f5b9a4", fg = "#4c2619", bold = true }
unset_alt  = { bg = "#4e444b", fg = "#d2c2cb" }




[select]
border = { fg = "#f3b2e3" }
active = { fg = "#f5b9a4", bold = true }




[input]
border = { fg = "#f3b2e3" }
value = { fg = "#ecdfe5" }



[tabs]
active = { fg = "#f3b2e3", bold = true, bg = "#181216" }
inactive = { fg = "#dbbed1", bg = "#181216" }
sep_inner = { open = "[", close = "]" }




[cmp]
border = { fg = "#f3b2e3", bg = "#4d1f46" }




[tasks]
border = { fg = "#f3b2e3" }
title = {}
hovered = { fg = "#ffdbcf", underline = true }




[which]
cols = 3
mask = { bg = "#3f373c" }
cand = { fg = "#f3b2e3" }
rest = { fg = "#4d1f46" }
desc = { fg = "#ecdfe5" }
separator = " ▶ "
separator_style = { fg = "#ecdfe5" }




[help]
on = { fg = "#ecdfe5" }
run = { fg = "#ecdfe5" }
footer = { fg = "#3e2a39", bg = "#dbbed1" }




[notify]
title_info = { fg = "#f5b9a4" }
title_warn = { fg = "#f3b2e3" }
title_error = { fg = "#ffb4ab" }




[filetype]

rules = [
    { mime = "image", fg = "#f3b2e3" },
]

