
cursor                #ebc16c
cursor_text_color     #402d00

foreground            #ebe1d4
background            #17130b
selection_foreground  #402d00
selection_background  #ebc16c
url_color             #ebc16c

color0   #17130b
color8   #3e382f

color1   #ffb4ab
color9   #93000a

color2   #b1cfa8
color10  #344d2f

color3   #d9c4a0
color11  #53452a

color4   #ebc16c
color12  #5c4200

color5   #b1cfa8
color13  #cdebc3

color6   #d9c4a0
color14  #f6e0bb

color7   #d1c5b4
color15  #ebe1d4
