
cursor                #e7c26c
cursor_text_color     #3f2e00

foreground            #ebe1d4
background            #17130b
selection_foreground  #3f2e00
selection_background  #e7c26c
url_color             #e7c26c

color0   #17130b
color8   #3e392f

color1   #ffb4ab
color9   #93000a

color2   #afcfab
color10  #324d31

color3   #d7c4a0
color11  #52452a

color4   #e7c26c
color12  #5a4300

color5   #afcfab
color13  #cbebc5

color6   #d7c4a0
color14  #f4e0bb

color7   #d0c5b4
color15  #ebe1d4
