
cursor                #ffb688
cursor_text_color     #512400

foreground            #f0dfd7
background            #19120d
selection_foreground  #512400
selection_background  #ffb688
url_color             #ffb688

color0   #19120d
color8   #413731

color1   #ffb4ab
color9   #93000a

color2   #caca93
color10  #48491e

color3   #e5bfa9
color11  #5b4130

color4   #ffb688
color12  #6e390f

color5   #caca93
color13  #e6e6ad

color6   #e5bfa9
color14  #ffdbc7

color7   #d7c3b8
color15  #f0dfd7
