#!/bin/bash

ON_TEMP=4000
OFF_TEMP=6000

if ! pgrep -x hyprsunset; then
  setsid uwsm-app -- hyprsunset &
  sleep 1 # Give it time to register
fi

CURRENT_TEMP=$(hyprctl hyprsunset temperature 2>/dev/null | grep -oE '[0-9]+')

if [[ "$CURRENT_TEMP" == "$OFF_TEMP" ]]; then
  hyprctl hyprsunset temperature $ON_TEMP
  notify-send "Nightlight" "Screen temperature: ${ON_TEMP}K"
else
  hyprctl hyprsunset temperature $OFF_TEMP
  notify-send "Nightlight" "Screen temperature: ${OFF_TEMP}K (disabled)"
fi
