#!/bin/bash

if ! command -v tte &>/dev/null; then
  exit 1
fi

pgrep -f "alacritty --class Screensaver" && exit 0

focused=$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')

for m in $(hyprctl monitors -j | jq -r '.[] | .name'); do
  hyprctl dispatch focusmonitor $m

  hyprctl dispatch exec -- \
    alacritty --class Screensaver \
    --config-file ~/.config/alacritty/screensaver.toml \
    -e ~/.config/hypr/scripts/screensaver
done

hyprctl dispatch focusmonitor $focused
