general {
    font_family = "Inter"
    font_size = 11
}

[Interface]
font-family=Inter
font-size=11
icon-theme=Adwaita
theme=current
cursor-theme=Bibata-Modern-Ice
cursor-size=24
dialogs-use-header=false
show-accessibility=true
show-button-images=false
show-menu-icons=true

[ColorScheme]
prefer-dark=true