
[mgr]
cwd = { fg = "#ece1d4" }

find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

marker_copied = { fg = "#98d172", bg = "#98d172" }
marker_cut = { fg = "#d0eabf", bg = "#d0eabf" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b4cea5", bg = "#b4cea5" }

count_copied = { fg = "#0c2006", bg = "#d0eabf" }
count_cut = { fg = "#0c2006", bg = "#d0eabf" }
count_selected = { fg = "#422c00", bg = "#b4cea5" }

border_symbol = " "
border_style  = { fg = "#f0bf6d" }




[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

perm_type = { fg = "#a47a3f" }
perm_read = { fg = "#7bc44c" }
perm_write = { fg = "#648d4d" }
perm_exec = { fg = "#ff2b12" }
perm_sep = { fg = "#ffa212" }

progress_label = { bold = true }
progress_normal = { fg = "#f0bf6d", bg = "#3f382f" }
progress_error = { fg = "#ffb4ab", bg = "#3f382f" }

[mode]
normal_main = { bg = "#f0bf6d", fg = "#422c00", bold = true }
normal_alt  = { bg = "#4e4539", fg = "#d2c5b4" }

select_main = { bg = "#dbc3a1", fg = "#3c2e16", bold = true }
select_alt  = { bg = "#4e4539", fg = "#d2c5b4" }

unset_main = { bg = "#b4cea5", fg = "#213618", bold = true }
unset_alt  = { bg = "#4e4539", fg = "#d2c5b4" }




[select]
border = { fg = "#f0bf6d" }
active = { fg = "#b4cea5", bold = true }




[input]
border = { fg = "#f0bf6d" }
value = { fg = "#ece1d4" }



[tabs]
active = { fg = "#f0bf6d", bold = true, bg = "#17130b" }
inactive = { fg = "#dbc3a1", bg = "#17130b" }
sep_inner = { open = "[", close = "]" }




[cmp]
border = { fg = "#f0bf6d", bg = "#422c00" }




[tasks]
border = { fg = "#f0bf6d" }
title = {}
hovered = { fg = "#d0eabf", underline = true }




[which]
cols = 3
mask = { bg = "#3f382f" }
cand = { fg = "#f0bf6d" }
rest = { fg = "#422c00" }
desc = { fg = "#ece1d4" }
separator = " ▶ "
separator_style = { fg = "#ece1d4" }




[help]
on = { fg = "#ece1d4" }
run = { fg = "#ece1d4" }
footer = { fg = "#3c2e16", bg = "#dbc3a1" }




[notify]
title_info = { fg = "#b4cea5" }
title_warn = { fg = "#f0bf6d" }
title_error = { fg = "#ffb4ab" }




[filetype]

rules = [
    { mime = "image", fg = "#f0bf6d" },
]

