
[mgr]
cwd = { fg = "#e0e4da" }

find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

marker_copied = { fg = "#6ad2db", bg = "#6ad2db" }
marker_cut = { fg = "#bcebef", bg = "#bcebef" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a0cfd3", bg = "#a0cfd3" }

count_copied = { fg = "#002022", bg = "#bcebef" }
count_cut = { fg = "#002022", bg = "#bcebef" }
count_selected = { fg = "#0e380d", bg = "#a0cfd3" }

border_symbol = " "
border_style  = { fg = "#a3d398" }




[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

perm_type = { fg = "#6a8a5b" }
perm_read = { fg = "#40c6d2" }
perm_write = { fg = "#458f95" }
perm_exec = { fg = "#ff2b12" }
perm_sep = { fg = "#52d732" }

progress_label = { bold = true }
progress_normal = { fg = "#a3d398", bg = "#363a34" }
progress_error = { fg = "#ffb4ab", bg = "#363a34" }

[mode]
normal_main = { bg = "#a3d398", fg = "#0e380d", bold = true }
normal_alt  = { bg = "#42493f", fg = "#c2c8bc" }

select_main = { bg = "#baccb2", fg = "#263422", bold = true }
select_alt  = { bg = "#42493f", fg = "#c2c8bc" }

unset_main = { bg = "#a0cfd3", fg = "#00363a", bold = true }
unset_alt  = { bg = "#42493f", fg = "#c2c8bc" }




[select]
border = { fg = "#a3d398" }
active = { fg = "#a0cfd3", bold = true }




[input]
border = { fg = "#a3d398" }
value = { fg = "#e0e4da" }



[tabs]
active = { fg = "#a3d398", bold = true, bg = "#11140f" }
inactive = { fg = "#baccb2", bg = "#11140f" }
sep_inner = { open = "[", close = "]" }




[cmp]
border = { fg = "#a3d398", bg = "#0e380d" }




[tasks]
border = { fg = "#a3d398" }
title = {}
hovered = { fg = "#bcebef", underline = true }




[which]
cols = 3
mask = { bg = "#363a34" }
cand = { fg = "#a3d398" }
rest = { fg = "#0e380d" }
desc = { fg = "#e0e4da" }
separator = " ▶ "
separator_style = { fg = "#e0e4da" }




[help]
on = { fg = "#e0e4da" }
run = { fg = "#e0e4da" }
footer = { fg = "#263422", bg = "#baccb2" }




[notify]
title_info = { fg = "#a0cfd3" }
title_warn = { fg = "#a3d398" }
title_error = { fg = "#ffb4ab" }




[filetype]

rules = [
    { mime = "image", fg = "#a3d398" },
]

