
[mgr]
cwd = { fg = "#ebe1d4" }

find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

marker_copied = { fg = "#87d179", bg = "#87d179" }
marker_cut = { fg = "#cbebc5", bg = "#cbebc5" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#afcfab", bg = "#afcfab" }

count_copied = { fg = "#062109", bg = "#cbebc5" }
count_cut = { fg = "#062109", bg = "#cbebc5" }
count_selected = { fg = "#3f2e00", bg = "#afcfab" }

border_symbol = " "
border_style  = { fg = "#e7c26c" }




[status]
sep_left = { open = "", close = "🭠" }
sep_right = { open = "🭁", close = "" }

perm_type = { fg = "#9c7d42" }
perm_read = { fg = "#65c453" }
perm_write = { fg = "#598f52" }
perm_exec = { fg = "#ff2b12" }
perm_sep = { fg = "#ffaf01" }

progress_label = { bold = true }
progress_normal = { fg = "#e7c26c", bg = "#3e392f" }
progress_error = { fg = "#ffb4ab", bg = "#3e392f" }

[mode]
normal_main = { bg = "#e7c26c", fg = "#3f2e00", bold = true }
normal_alt  = { bg = "#4d4639", fg = "#d0c5b4" }

select_main = { bg = "#d7c4a0", fg = "#3a2f15", bold = true }
select_alt  = { bg = "#4d4639", fg = "#d0c5b4" }

unset_main = { bg = "#afcfab", fg = "#1c361d", bold = true }
unset_alt  = { bg = "#4d4639", fg = "#d0c5b4" }




[select]
border = { fg = "#e7c26c" }
active = { fg = "#afcfab", bold = true }




[input]
border = { fg = "#e7c26c" }
value = { fg = "#ebe1d4" }



[tabs]
active = { fg = "#e7c26c", bold = true, bg = "#17130b" }
inactive = { fg = "#d7c4a0", bg = "#17130b" }
sep_inner = { open = "[", close = "]" }




[cmp]
border = { fg = "#e7c26c", bg = "#3f2e00" }




[tasks]
border = { fg = "#e7c26c" }
title = {}
hovered = { fg = "#cbebc5", underline = true }




[which]
cols = 3
mask = { bg = "#3e392f" }
cand = { fg = "#e7c26c" }
rest = { fg = "#3f2e00" }
desc = { fg = "#ebe1d4" }
separator = " ▶ "
separator_style = { fg = "#ebe1d4" }




[help]
on = { fg = "#ebe1d4" }
run = { fg = "#ebe1d4" }
footer = { fg = "#3a2f15", bg = "#d7c4a0" }




[notify]
title_info = { fg = "#afcfab" }
title_warn = { fg = "#e7c26c" }
title_error = { fg = "#ffb4ab" }




[filetype]

rules = [
    { mime = "image", fg = "#e7c26c" },
]

