#!/bin/bash
[[ -n "${_N4P1X_ENV_SH:-}" ]] && return 0
readonly _N4P1X_ENV_SH=1

# Core directories
N4P1X_DIR="${HOME}/.config/N4P1x"
N4P1X_EXTERNAL="${HOME}/N4P1x"
N4P1X_CACHE_DIR="${HOME}/.cache/N4P1x"
N4P1X_STATE_DIR="${HOME}/.local/state/N4P1x"
N4P1X_SCRIPTS="${HOME}/.config/hypr/scripts"
N4P1X_LIB="${N4P1X_SCRIPTS}/lib/common.sh"
N4P1X_THEME_SCRIPTS="${N4P1X_SCRIPTS}/theme"
N4P1X_SYSTEM_SCRIPTS="${N4P1X_SCRIPTS}/system"
N4P1X_ROFI_SCRIPTS="${HOME}/.config/rofi/scripts"

# Key files
N4P1X_CURRENT_THEME="${N4P1X_DIR}/.current-theme"
N4P1X_CURRENT_WALL="${N4P1X_DIR}/current/wallpaper"
N4P1X_CURRENT_CONFIG="${N4P1X_DIR}/current/.config"
N4P1X_MATUGEN_CONFIG="${HOME}/.config/matugen/config.toml"
N4P1X_SYNC_SCRIPT="${N4P1X_THEME_SCRIPTS}/sync-all"
N4P1X_VERIFY_SCRIPT="${N4P1X_THEME_SCRIPTS}/verify"
N4P1X_INFO_SCRIPT="${N4P1X_THEME_SCRIPTS}/info"
N4P1X_WALLSET_SCRIPT="${N4P1X_SCRIPTS}/wallset.sh"
N4P1X_CYCLE_SCRIPT="${N4P1X_THEME_SCRIPTS}/cycle-wallpaper"
N4P1X_MONITOR_SCRIPT="${N4P1X_SYSTEM_SCRIPTS}/monitor"
N4P1X_APPLY_SCRIPT="${N4P1X_SYSTEM_SCRIPTS}/apply-optimizations"
N4P1X_AUTO_OPTIMIZE_SCRIPT="${N4P1X_SYSTEM_SCRIPTS}/auto-optimize"
N4P1X_CENTER_SCRIPT="${N4P1X_SYSTEM_SCRIPTS}/center"
N4P1X_DASHBOARD_SCRIPT="${N4P1X_SYSTEM_SCRIPTS}/dashboard"
N4P1X_FIRST_RUN_MARKER="${N4P1X_STATE_DIR}/first-run-done"
N4P1X_CLI="${N4P1X_DIR}/N4P1x"
N4P1X_TUI="${N4P1X_DIR}/N4P1x-tui"

# Wallpaper
N4P1X_BG_DIR="${HOME}/Pictures/Wallpapers"
N4P1X_BG_DIR_FALLBACK="${HOME}/Wallpapers"

# Lock files
N4P1X_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp}"
N4P1X_WALL_LOCK="${N4P1X_RUNTIME_DIR}/N4P1x-wallpaper.lock"
N4P1X_WALL_STAMP="${N4P1X_RUNTIME_DIR}/N4P1x-wallpaper.last"
N4P1X_MATUGEN_LOCK="${N4P1X_RUNTIME_DIR}/N4P1x-matugen.lock"
