
[colors.primary]
background = '#19120d'
foreground = '#f0dfd7'

[colors.cursor]
cursor = '#ffb688'
text = '#512400'

[colors.vi_mode_cursor]
cursor = '#ffb688'
text = '#512400'

[colors.search.matches]
foreground = '#32320a'
background = '#caca93'

[colors.search.focused_match]
foreground = '#512400'
background = '#ffb688'

[colors.footer_bar]
foreground = '#f0dfd7'
background = '#261e19'

[colors.hints.start]
foreground = '#432b1c'
background = '#e5bfa9'

[colors.hints.end]
foreground = '#432b1c'
background = '#5b4130'

[colors.selection]
text = '#512400'
background = '#ffb688'

[colors.normal]
black   = '#19120d'
red     = '#ffb4ab'
green   = '#caca93'
yellow  = '#e5bfa9'
blue    = '#ffb688'
magenta = '#caca93'
cyan    = '#e5bfa9'
white   = '#d7c3b8'

[colors.bright]
black   = '#413731'
red     = '#93000a'
green   = '#48491e'
yellow  = '#5b4130'
blue    = '#6e390f'
magenta = '#e6e6ad'
cyan    = '#ffdbc7'
white   = '#f0dfd7'

[colors.dim]
black   = '#140d08'
red     = '#ffdad6'
green   = '#e6e6ad'
yellow  = '#ffdbc7'
blue    = '#ffdbc7'
magenta = '#1c1d00'
cyan    = '#2b1709'
white   = '#9f8d83'
