
[colors.primary]
background = '#19120c'
foreground = '#eee0d5'

[colors.cursor]
cursor = '#faba73'
text = '#482900'

[colors.vi_mode_cursor]
cursor = '#faba73'
text = '#482900'

[colors.search.matches]
foreground = '#293411'
background = '#becc9c'

[colors.search.focused_match]
foreground = '#482900'
background = '#faba73'

[colors.footer_bar]
foreground = '#eee0d5'
background = '#251e17'

[colors.hints.start]
foreground = '#402d17'
background = '#e0c1a3'

[colors.hints.end]
foreground = '#402d17'
background = '#58432c'

[colors.selection]
text = '#482900'
background = '#faba73'

[colors.normal]
black   = '#19120c'
red     = '#ffb4ab'
green   = '#becc9c'
yellow  = '#e0c1a3'
blue    = '#faba73'
magenta = '#becc9c'
cyan    = '#e0c1a3'
white   = '#d4c4b5'

[colors.bright]
black   = '#403830'
red     = '#93000a'
green   = '#3f4b26'
yellow  = '#58432c'
blue    = '#673d00'
magenta = '#dae9b6'
cyan    = '#feddbd'
white   = '#eee0d5'

[colors.dim]
black   = '#130d07'
red     = '#ffdad6'
green   = '#dae9b6'
yellow  = '#feddbd'
blue    = '#ffdcbb'
magenta = '#141f01'
cyan    = '#281805'
white   = '#9d8e81'
