
[colors.primary]
background = '#181216'
foreground = '#ecdfe5'

[colors.cursor]
cursor = '#f3b2e3'
text = '#4d1f46'

[colors.vi_mode_cursor]
cursor = '#f3b2e3'
text = '#4d1f46'

[colors.search.matches]
foreground = '#4c2619'
background = '#f5b9a4'

[colors.search.focused_match]
foreground = '#4d1f46'
background = '#f3b2e3'

[colors.footer_bar]
foreground = '#ecdfe5'
background = '#241e22'

[colors.hints.start]
foreground = '#3e2a39'
background = '#dbbed1'

[colors.hints.end]
foreground = '#3e2a39'
background = '#554050'

[colors.selection]
text = '#4d1f46'
background = '#f3b2e3'

[colors.normal]
black   = '#181216'
red     = '#ffb4ab'
green   = '#f5b9a4'
yellow  = '#dbbed1'
blue    = '#f3b2e3'
magenta = '#f5b9a4'
cyan    = '#dbbed1'
white   = '#d2c2cb'

[colors.bright]
black   = '#3f373c'
red     = '#93000a'
green   = '#663c2d'
yellow  = '#554050'
blue    = '#67355e'
magenta = '#ffdbcf'
cyan    = '#f8daed'
white   = '#ecdfe5'

[colors.dim]
black   = '#120c10'
red     = '#ffdad6'
green   = '#ffdbcf'
yellow  = '#f8daed'
blue    = '#ffd7f2'
magenta = '#321206'
cyan    = '#271623'
white   = '#9a8d95'
