[General]
sessions=0

[MainWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x5\x39\0\0\x2\xc5\0\0\0\0\0\0\0\0\0\0\x2\x9e\0\0\x2\xc9\0\0\0\0\x2\0\0\0\x5V\0\0\0\0\0\0\0\0\0\0\x5\x39\0\0\x2\xc5)
state=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x5:\0\0\x2\xc6\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[Settings]
Dec_ExportFormat=%s %d: %r: %1
General_Language=en
General_SaveWithSetup=true
General_Style=
General_Theme=0
Log_BufferSize=500
Log_NotifyOfStacktrace=true
View_ColoredBG=true
View_CursorFillColor=4292667379
View_CursorShowFrequency=true
View_CursorShowInterval=true
View_DefaultDivHeight=51
View_DefaultLogicHeight=34
View_FillSignalHighAreaColor=201326592
View_FillSignalHighAreas=true
View_ShowHoverMarker=true
View_ShowSamplingPoints=true
View_SnapDistance=15
View_ZoomToFitAfterAcq=true
