#!/bin/bash

source "${BASH_SOURCE[0]%/*}/../../../N4P1x/env.sh"

T=$(cat "$N4P1X_CURRENT_THEME")
SRC="$N4P1X_DIR/$T/.config"

echo "Theme: $T"
echo ""

BG=$(grep "^@define-color background" "$SRC/gtk-3.0/colors.css" | sed 's/.*#\([0-9a-fA-F]*\).*/\1/')
FG=$(grep "^@define-color foreground" "$SRC/gtk-3.0/colors.css" | sed 's/.*#\([0-9a-fA-F]*\).*/\1/')
ACCENT=$(grep "^@define-color blue" "$SRC/gtk-3.0/colors.css" | sed 's/.*#\([0-9a-fA-F]*\).*/\1/')

echo "Colors:"
echo "  Background: #$BG"
echo "  Foreground: #$FG"
echo "  Accent:     #$ACCENT"
echo ""

echo "Configs: $(ls "$SRC" | wc -l)"
echo "Apps: $(ls "$SRC" | paste -sd ', ')"