
cursor                #faba73
cursor_text_color     #482900

foreground            #eee0d5
background            #19120c
selection_foreground  #482900
selection_background  #faba73
url_color             #faba73

color0   #19120c
color8   #403830

color1   #ffb4ab
color9   #93000a

color2   #becc9c
color10  #3f4b26

color3   #e0c1a3
color11  #58432c

color4   #faba73
color12  #673d00

color5   #becc9c
color13  #dae9b6

color6   #e0c1a3
color14  #feddbd

color7   #d4c4b5
color15  #eee0d5
