
cursor                #f0bf6d
cursor_text_color     #422c00

foreground            #ece1d4
background            #17130b
selection_foreground  #422c00
selection_background  #f0bf6d
url_color             #f0bf6d

color0   #17130b
color8   #3f382f

color1   #ffb4ab
color9   #93000a

color2   #b4cea5
color10  #374d2d

color3   #dbc3a1
color11  #55442a

color4   #f0bf6d
color12  #5f4100

color5   #b4cea5
color13  #d0eabf

color6   #dbc3a1
color14  #f8dfbb

color7   #d2c5b4
color15  #ece1d4
